### ISSUE TITLE
The mod FEI (Forever Enough Items) requires mod versions [excore@[1.5,)] to be available

### ISSUE THREAD

**Issue by ghost** [elix-x/Forever-Enough-Items#1]
for your information
Am I to fast - perhaps?
best regards jokish

**Comment by Elix-x** [comment]
Very massive derp on my part. I forgot to hit submit button when uploaded files to curse. Sorry about that.

Meanwhile, they're already approved!
Here's direct link: http://minecraft.curseforge.com/projects/excore/files/2296129

**Comment by ghost** [comment]
thank you for your fast response

best regards jokish

**Comment by Elix-x** [comment]
No problems!
BTW, you're faaaaar not the only one who reported this.
