### ISSUE TITLE
[Issue] Permanent Rain

### ISSUE THREAD

**Issue by accessdenied0** [elix-x/Forever-Enough-Items#10]
Hey @elix-x,

I recently found a bug with this mod (ForeverEnoughItems-1.0.8-1.9, Forge: 12.16.1.1887)

It seem to set constantly the rain to "true" (seem not to save a state change). I was not able to turn it off with normal ways (sleeping) or cheats like (toggledownfall). Sadly I do not have proof in form of a console message, but after disabling this mod (and only this one) it is working again.

thanks for your help,

access_denied

**Comment by Elix-x** [comment]
Are you speaking of weather utility?

**Comment by accessdenied0** [comment]
@elix-x 

Yeah. I was like I said not able to change the weather. It always turned to rain. Even the features were in Recipe-, Utility- or Cheat- mode, the results were the same. Rain turned "off" and immediately back on. Even the button only showed, after closing and reopening, the next option after rain (Thunderstorm).

**Comment by Elix-x** [comment]
And if you click on clear (Right click on weather util and click on the sun)? Does the rain disappear?

**Comment by accessdenied0** [comment]
@elix-x 

It always seem to stop the rain (rain fades out, it getting brighter, sun) but after this "animation" is finished it immediately starts to rain again. If I try after this to turn the rain "on" again, it also stops for a brief second and it starts raining, again, again.

**Comment by Elix-x** [comment]
That's weird. And if you use command will the rain restart again?

**Comment by accessdenied0** [comment]
@elix-x 

Yeah. Commands, Beds and FEI (integrated button). Nothing worked.

**Comment by Elix-x** [comment]
That's very weird... Have never seen antyhing like this.
I'll look into what might be causing this, meanwhile which other mods do you have installed?

**Comment by accessdenied0** [comment]
Here: http://pastebin.com/1E3QFgn0

**Comment by Elix-x** [comment]
Wow... That's a not a small modpack.
I quickly looked through it, but haven't noticed any mod that could affect weather. Can you think of any?

**Comment by accessdenied0** [comment]
127 mods, sadly I can't tell which one could affect weather. The only one I can spontaneously think of is Blood-Magic. The rest is more tech-mod stuff (so no direct effects to weather).

**Comment by Elix-x** [comment]
Ok... I have tried searching for it, did not find.
Is this bug specific to one world, or does it happen in all worlds?

**Comment by accessdenied0** [comment]
@elix-x 

Sorry for let ya waiting for so long, I got a bit busy lately....

Anyway I updated a few mods and strangely it seem to be fixed.... I don't know which mod it caused...

I think we can close it for now... I hope this doesn't happen again ;)

Thank you anyway for your help.

**Comment by Elix-x** [comment]
Yeah, we can close it. It's probably mod interaction. Weird things happen with it.
I'm glad it's fixed, though.
