### ISSUE TITLE
Crash loading on Server

### ISSUE THREAD

**Issue by timmyow** [elix-x/Forever-Enough-Items#11]
Server crashes on load with this crash when FEI is in the instance.
JEI 1.9-3.3.3.197
Excore 1.5.3-1.9
ForeverEnoughItems-1.0.8-1.9

http://pastebin.com/43kkDEG6

**Comment by Elix-x** [comment]
Thanks for the report. It's partially known for a week already, but i still can't figure out what's exactly causing it.

**Comment by Bennyboy1695** [comment]
Looks like the issue might be this line - https://github.com/elix-x/Forever-Enough-Items/blob/master/1.9/src/main/java/code/elix_x/mods/fei/utils/BinFEIUtil.java#L20
the code "thePlayer" is calling the singleplayer version of the player rather then multiplayer which is needed on servers obviously.

**Comment by Elix-x** [comment]
No. In java class is loaded when it:
-Is defined as field of class that is being loaded.
-Is required in currently executed method.
So unless onSelect is executed, class will not be loaded (but it would try to load Minecraft first and fail anyways).

**Comment by Bennyboy1695** [comment]
I know how java works, have written mods myself :stuck_out_tongue: 
But the reason this wont work is because the server is trying to use a Client only class meaning its going to always crash.
This is what the crash report tells you - Attempted to load class net/minecraft/client/entity/EntityPlayerSP for invalid side SERVER.

**Comment by Elix-x** [comment]
I'll just say that if you haven't looked a lot at code, don't say anything. I'll stop here.
Class is not loaded until mehtod is ran. And in this case especially, it would try to load Minecraft (which is also client side) first and crash on it without reaching SP.
