### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by mik900** [elix-x/Forever-Enough-Items#12]
Server crashes with FEI installed.
Installed mods:
 Excore-1.5.3-1.9
 ForeverEnoughItems-1.0.9-1.9
 jei_1.9-3.3.3.200
Crashlog:
http://pastebin.com/5mgSAbwt

**Comment by Elix-x** [comment]
Weird. Didn't meet this one while testing. Will be hotfixed.

**Comment by Elix-x** [comment]
I get it. This class is client only in 1.8, but not in 1.9.

**Comment by mik900** [comment]
Sorry for the inconvenience, but my MC-version is 1.9

**Comment by Elix-x** [comment]
Ok. Aparently i messed up in both places.
