### ISSUE TITLE
Server crash on Player join [MC1.9, ForeverEnoughItems-1.0.9.1-1.9]

### ISSUE THREAD

**Issue by mik900** [elix-x/Forever-Enough-Items#14]
crash when a Player join on the server.
Mods:
- Excore-1.5.3-1.9.jar
- jei_1.9-3.3.3.200.jar
- ForeverEnoughItems-1.0.9.1-1.9.jar
- Mantle-1.9-0.9.4.jar
- TConstruct-1.9-2.2.2.jar

[crash-report](http://pastebin.com/xbpwTzSm)

**Comment by Elix-x** [comment]
Ok... Anything else XD... ?

**Comment by mik900** [comment]
:smiley: Not in the Moment.
Server starts normally, but on player join, server crash.

**Comment by Elix-x** [comment]
Ok. I'll fix this, not right right now. Maybe in an hour fix will be out.

**Comment by mik900** [comment]
👍

**Comment by mik900** [comment]
Now it works fine for me. 👍 Thanks for the fix. 😃

**Comment by Elix-x** [comment]
You're welcome! :smile: !
