### ISSUE TITLE
Crash on MIneplex?

### ISSUE THREAD

**Issue by MineWitherMC** [elix-x/Forever-Enough-Items#15]
When I trying to get to mineplex server with FEI my client crashes. It doesn't crash without FEI nor it crashes on other servers.
Crash Report: http://codepad.org/YXfrXZl7
Edit: it crashes when opening inventory.

**Comment by Elix-x** [comment]
And i does not crash with fei on any other server? Interesting...
Anyways, i'll look into it.

**Comment by Elix-x** [comment]
Can you try to reproduce this with 1.0.11, please?

**Comment by Elix-x** [comment]
Without any new reports, this will be considered as fixed.
