### ISSUE TITLE
Crash on /feiop

### ISSUE THREAD

**Issue by xCaptainHaddockx** [elix-x/Forever-Enough-Items#17]
Whenever I use the /feiop command in single player, my game crashes shortly afterwards.  The crash usually results within 5 - 15 seconds of the command, but has taken close to 45 seconds to a minute on occasion.  My crash report mentions an OpenGL error, but I don't know why this command would interfere with OpenGL.  Additionally, my graphics drivers are all up to date.

Crash report:  http://pastebin.com/a9K41iXH
Latest.log:      http://pastebin.com/eHhB57Kg

Any help would be greatly appreciated.

**Comment by Elix-x** [comment]
Actually, this has nothing to do with GL.

> `java.lang.AbstractMethodError`

**Comment by Elix-x** [comment]
Just noticed: you're using 1.9.4 versions for mc 1.9. Either download 1.9 excore & FEI versions or update forge to 1.9.4.

**Comment by xCaptainHaddockx** [comment]
Thanks for the reply.  I had tried running with forge 1.9.4 before, but was getting a crash on startup.  I just updated again though, and it seems the problem was with an incompatible version of Optifine rather than with your mod.  Thanks for the help, love your mod.

**Comment by Elix-x** [comment]
Nice. So is everything working now?

**Comment by xCaptainHaddockx** [comment]
Yep.  Updated Optifine, and everything's running smoothly.

**Comment by Elix-x** [comment]
Ok. Good to know.
