### ISSUE TITLE
Overlay Not Like Described

### ISSUE THREAD

**Issue by billybag** [elix-x/Forever-Enough-Items#18]
I have no idea what i am doing wrong, the mod works, but the overlay is not like pictured or described and there is no "profiles" button or any settings button. Hitting "P" does nothing. The left arrow (used to scroll through items) is covered up with a big subsets button.

Also is there a thread for this in the Minecraft forum because i looked and couldn't find one and it would probably be wise to do so.

**Comment by billybag** [comment]
solved by deleting and reinstalling JEI and deleting all config files.

**Comment by Elix-x** [comment]
Ok. Something simply glitched out. Good that you managed to fix it!

MCF thread will come when i will finish documentation on curse. Because MCF editor is very derpy and i don't want to edit information there 9000 times.
