### ISSUE TITLE
Crash when trying to type in the search box

### ISSUE THREAD

**Issue by Renadarain** [elix-x/Forever-Enough-Items#20]
Hi,

Minecraft: 1.9.4
Forge: forge-1.9.4-12.17.0.1965 & forge-1.9.4-12.17.0.1968
Jei: jei_1.9.4-3.6.7.216
ForeverEnoughItems-1.0.10-1.9.4

Tried with and without a texture pack, With and without any mods. (Except jei and fei)

http://pastebin.com/ain6XR5x

Regards,
Renada

**Comment by Elix-x** [comment]
And if you try with jei_1.9.4-3.4.0.204.jar, does it still crash?

**Comment by Renadarain** [comment]
Just tested with jei_1.9.4-3.4.0.204.jar with no other mods and it doesn't crash but I can't test it with the mods as apparently some of them require the latest jei.

**Comment by Elix-x** [comment]
Ok, thanks. Seems to be FEI overrides' problem with latest JEI. I'll push hotfix tomorrow (unable to do it today).

**Comment by Renadarain** [comment]
Thanks very much, appreciate that  :)

**Comment by Elix-x** [comment]
You're welcome!
