### ISSUE TITLE
Crashing on Startup 1.8.9 - Improving Minecraft - ItemMobSpawner.func_150895_a

### ISSUE THREAD

**Issue by LemonJamTart** [elix-x/Forever-Enough-Items#21]
Hello! I've been having a bit of a crashing issue when I attempt to even launch the game. After removing all of my mods except for FEI, JEI, and Excore, the game launches just fine. I have a crash report on this Google Doc [here](https://docs.google.com/document/d/1rmLuwUTHH-hTs_z_caryXgZo0ahPXbHWjvS38zSeZ_c/edit). If you could perhaps take a look at that, and help me identify which mod I've got installed is the problem, I would greatly appreciate it, and if you need anything else I'll do my best to provide.

Latest version of FEI, the latest 1.8.9 version of JEI (which I believe is 2.28.18.186), Excore 1.5.3

**Comment by Elix-x** [comment]
Uhhm, you didn't open crash file to public access.
And it would be better, if you could post it on patebin or gist.

**Comment by LemonJamTart** [comment]
Oh! Oh, gosh, I'm so sorry! I have a new, working Pastebin link [here](http://pastebin.com/JprZW0xt). Very sorry.

**Comment by Elix-x** [comment]
No, not a big deal.
Looking at this crash, it actually is weird and caused by a mod.

Ok, in your opinion, which of mods that you have have somethign to do with spawners (really anything, from texture changing to complete overhaul)?

**Comment by Elix-x** [comment]
It's crash with Improving Minecraft, you can report it on [his issue tracker](http://minecraft.curseforge.com/projects/improving-minecraft/issues/create). While it's not fixed, i'll keep this issue open.

**Comment by LemonJamTart** [comment]
Oh, ok, thank you! I don't really need the mod, as I added it as an afterthought, so I can just remove it. Thank you very much. I'll go ahead and report it on his issue tracker so that it might help him with conflicting mods.

**Comment by Elix-x** [comment]
Thanks for reporting it to him!
As issue is on his side, i'll consider this issue on my side fixed.
