### ISSUE TITLE
Minecraft 1.10 server - Forge installed client crash when clicking item - NoSuchMethodError Focus.getStack

### ISSUE THREAD

**Issue by SerranoPancake** [elix-x/Forever-Enough-Items#23]
Got mod installed on server. Logged in, everything looked good. Able to change profiles no problem. When I go into cheat mode and click an item to get a stack or right click for one, the client crashes with this error log.
http://pastebin.com/Tmz6C4Fw

Thanks in advance for the help! Great Mod

**Comment by Elix-x** [comment]
Thanks for the report. I think i know what happened.

**Comment by Elix-x** [comment]
Fixed wrong thing.
