### ISSUE TITLE
Forever Enough Items Crash When Click For Stack

### ISSUE THREAD

**Issue by onangelswings** [elix-x/Forever-Enough-Items#25]
Hey i know you have just done an update, i downloaded that update and still the cheat mode does not work for me i am persistently getting a crash when trying to add items or stacks to my inventory,

I do /feiop and then go to inventory under cheat mode, example click diamond axe, game freezes, shutting down internal server and then the crash log.
Crash log below
[ pastebin.com/raw/VYchDntn](url)

**Comment by Elix-x** [comment]
Duplicate of #24 . It will be fixed, i "fixed" wrong thing in 1.0.13.

**Comment by onangelswings** [comment]
ah thanks, no problems i will check back later for your update then
