### ISSUE TITLE
OP Crasshes

### ISSUE THREAD

**Issue by PedroPTJuniorGames** [elix-x/Forever-Enough-Items#28]
I've installed this mod to help me fin the recipies without havint to leave the game screen, but i decided to use it to get some itens and when i usede the comand "/feiop" it triged a game crash, everytime i clic onto something (minecraft itnes) in the FEI/JEI menu the game crashes

Here is the game crash report.
[crash-2016-07-03_11.07.01-client.txt](https://github.com/elix-x/Forever-Enough-Items/files/345099/crash-2016-07-03_11.07.01-client.txt)

MODs:
1.10-chunkedgeindicator-1.3
Excore-1.5.3-1.9 (Not a MOD)
ForeverEnoughItems-1.0.12-1.10
jei_1.10.2-3.7.3.221
justbackpacks-mc1.9.4-1.0.2
LLOverlayReloaded-1.0.7-mc1.10
Xaeros_Minimap_1.9.6_Forge_1.10.2
XRay-31

PS.: i didn't have this problems with the 1.9.4 version, same mods

**Comment by Elix-x** [comment]
Fixed in 1.0.14.

**Comment by PedroPTJuniorGames** [comment]
thankyou

**Comment by Elix-x** [comment]
You're welcome.
