### ISSUE TITLE
Null item in itemStack java.lang.NullPointerException (plugins)

### ISSUE THREAD

**Issue by Gamerbolts** [elix-x/Forever-Enough-Items#29]
Hi I have not experienced a crash yet but was having a problem with a mod so went back to tested mods one at a time. I am seeing a lot of red text in the log. Not sure if it means anything? Any help is appreciated. Thank you!

http://pastebin.com/P1Pb5k27

I am using 1.10.2 newest version of FEI ; 1.10.2 Release version of JEI (I also tried the beta version: same error in the log) and the newest version of Excore

**Comment by Elix-x** [comment]
This seems to be JEI's "invalid" recipes logging. Totally normal and not related to FEI. Won't cause a crash though.
