### ISSUE TITLE
[Feature Change Request] Why do I have to use /feiop in singleplayer with cheats enabled?

### ISSUE THREAD

**Issue by GazbonicAcid** [elix-x/Forever-Enough-Items#30]
Why do I have to use /feiop in singleplayer with cheats enabled?
That just doesn't seem right to me.
I shouldn't have to use a command to be able to cheat items in when jei's cheat-items-in is enabled and cheats are enabled for the sp world.
Why can't you just use JEI's cheat-items-function instead of using your own function to cheat them in?
I think this because JEI's built in cheat mode can only cheat items in in singleplayer if cheats are enabled for the sp world you're playing in.
Because when JEI cheat-mode is enabled, but cheats are turned off for the world, and you try to use JEI to cheat an item inyou don't get the item.
Instead you get this error message in chat in red "You do not have permission to use that command!"
Therefore the only believable reason you would need to have an /feiop command is if FEI uses it's own method of cheating items in and does NOT use JEI to cheat items in.

**Comment by GazbonicAcid** [comment]
If however, you do use JEI to cheat items in,
I suggest you default the player to "OWNER" when when in a single player world with cheats enabled.

**Comment by Elix-x** [comment]
Well, i actually already got this request and i tried implemeting auto opping. [Sadly, it did not work](https://github.com/elix-x/Forever-Enough-Items/commit/04150d5b0e401ae5ca09a1070c650b6753615a03). I will try once more for next version, though. I might know a way around it.

**Comment by Elix-x** [comment]
Alright, i have good news and not so good news:
- I made it work.
- It will come in 1.1 update.

**Comment by GazbonicAcid** [comment]
if only I knew what makes the bad news, bad news.

**Comment by Elix-x** [comment]
That's up to you ;D.
