### ISSUE TITLE
Magnet toggle doesn't appear to work

### ISSUE THREAD

**Issue by Renadarain** [elix-x/Forever-Enough-Items#31]
Hi :)

MC: 1.10.2
forge-1.10.2-12.18.1.2026-installer
ForeverEnoughItems-1.0.15-1.10.2

Magnet is set to USER in the configs.  We can all use it but nobody can successfully turn it off again. You can click to turn it off but it doesn't actually turn off.  /magnet also gives "unknown command" error.

Regards,
Renada

**Comment by Elix-x** [comment]
You double click it (turn it on and back off).
There's a sync issue, which will be fixed in 1.1.

**Comment by Renadarain** [comment]
Thank you, that works :)
