### ISSUE TITLE
Crash starting in 1.10.2

### ISSUE THREAD

**Issue by huantianad** [elix-x/Forever-Enough-Items#33]
This is the crash report:
[crash-2016-07-31_16.11.16-client.txt](https://github.com/elix-x/Forever-Enough-Items/files/392692/crash-2016-07-31_16.11.16-client.txt)

**Comment by Eaglexxv** [comment]
elix-x 
thanks for your hard work. I'm also crash at start. But also it might be I'm running chisels and bits. Im not sure, so here is the crash report.
please let me know if I can help you out finding this or any other problems
thanks 
Eaglexxv
[crash-2016-07-31_20.41.29-client.txt](https://github.com/elix-x/Forever-Enough-Items/files/392756/crash-2016-07-31_20.41.29-client.txt)

**Comment by huantianad** [comment]
This has nothing to do with this, but how do you add a label?

**Comment by Elix-x** [comment]
Try updating excore to 1.6.1
If it didn't help, check that you have all required mods for all mods to run.

**Comment by Elix-x** [comment]
@dddwefesx labels can be added only by repo owners/modders.

**Comment by huantianad** [comment]
Thanks. That really helped!

**Comment by Elix-x** [comment]
Ok. Closing this...

Meanwhile i think we found a bug in forge :laughing: .
