### ISSUE TITLE
[1.10.2] Crash Due to Unknown character '' in '/config/JEI/jei.cfg:1'

### ISSUE THREAD

**Issue by Morpheus1101** [elix-x/Forever-Enough-Items#34]
Crash report @ http://pastebin.com/TUcUw1Wv

**Comment by Elix-x** [comment]
You can try deleting JEI/JEI.cfg. If you don't can't delete it, open it and replace all `'` characters with space.

**Comment by Morpheus1101** [comment]
I del all configs to let it re-generate and it come back up with the same error. I will try your suggestion though.

Going through the config, no character of ' appears in there, so the problem still exists making the mod unusable presently.

**Comment by Morpheus1101** [comment]
With JEI having been updated a couple times since this report, the issue still exists despite removing the JEI config's

**Comment by Elix-x** [comment]
You can also try deleting FEI/profiles/[each]/JEI. This may not help though.

**Comment by Morpheus1101** [comment]
Im running JEI//FEI etc all clientside only

**Comment by Elix-x** [comment]
Thanks. This does not help much though.

**Comment by Morpheus1101** [comment]
I can only go by the crash report, that hasnt changed, saying invalid character, but on my screen in the report the invalid character shjows as a Square box

**Comment by Elix-x** [comment]
> deleting FEI/profiles/[each]/JEI

Didn't help i suspect?

**Comment by Morpheus1101** [comment]
No, afraid it does nothing
![fei](https://cloud.githubusercontent.com/assets/10524952/17618566/d400083a-60c3-11e6-93c5-384228e3cc1b.png)

**Comment by Elix-x** [comment]
And when you go to `/config/JEI/jei.cfg`, which is first/second character (you can post config if you want)?

**Comment by Morpheus1101** [comment]
[jei.txt](https://github.com/elix-x/Forever-Enough-Items/files/415017/jei.txt)

**Comment by Elix-x** [comment]
I had to google this. For everybody, config reset helps. In this case it does not, meaning that it auto corrupts while generating for some reason.

So this is either JEI's or forge's issue. Try removing FEI and see if it fixes it.

**Comment by Morpheus1101** [comment]
I remove FEI it does indeed fix the issue

**Comment by Morpheus1101** [comment]
12.18.1.2050 Forge Version im using, 1.0.15 FEI, 3.8.0.241 JEI

**Comment by Elix-x** [comment]
Then i don't know where it's coming from... And why nobody reported something like this before.

Last thing you may try is renaming your `config` folder to `config_` and relaunching mc (basically regenerating all configs).

**Comment by Morpheus1101** [comment]
Ok this time around what ever changed in the last 2 days removing all configs this time and regenerating did indeed solve the issue

**Comment by Elix-x** [comment]
Glad it's fixed.

Absolutely weird bug. Hopefully no one ever meets it again.

**Comment by Morpheus1101** [comment]
Indeed, certainly not in the realm of normal for bugs

**Comment by elix-x** [comment]
For some reasons, it was reading wrong character. Sources of this bug can be anywhere between forge ch

**Comment by Elix-x** [comment]
For some reasons, it was reading wrong character. Sources of this bug can be anywhere between forge's charset used to NTFS bugs to hardware.

**Comment by Morpheus1101** [comment]
good god, that is such a massively wide range of area if a debug was needed to track the issue should it not have resolved itself.

**Comment by Elix-x** [comment]
Yup.
(And dealing with NTFS / OS bugs is a pain, trust me).
<sub><sup>_I had to deal with some recently_</sup></sub>
