### ISSUE TITLE
Crash with FEI

### ISSUE THREAD

**Issue by DatrixTHLK** [elix-x/Forever-Enough-Items#36]
JEI: 3.7.10.237
FEI: 1.0.15
forge: 12.18.1.2046
Crash Log: http://pastebin.com/EuBwpMYi
CTD's every time I try to get minecraft to open up.

**Comment by DatrixTHLK** [comment]
After I downgraded from 2046 to 2043 the errors went away. It is forge's update that caused mods to break. I shall close the issue.

**Comment by Elix-x** [comment]
Duplicate of #33.

TLDR: Check that you have latest excore.

**Comment by Elix-x** [comment]
Meanwhile, thanks for forge versions. Now i know that somebody's PR between 2043 and 2046 broke this.
