### ISSUE TITLE
Minecraft crashes (Help)

### ISSUE THREAD

**Issue by yagizcamo93** [elix-x/Forever-Enough-Items#37]
I installed all of the necessary mods but it crashes in the loading screen.

[crash-2016-09-01_02.04.16-client.txt](https://github.com/elix-x/Forever-Enough-Items/files/448458/crash-2016-09-01_02.04.16-client.txt)
[latest.txt](https://github.com/elix-x/Forever-Enough-Items/files/448459/latest.txt)

**Comment by Elix-x** [comment]
Duplicate of #33.

**Comment by Elix-x** [comment]
TLDR: Update excore to 1.6.2/1.6.1.
