### ISSUE TITLE
Looking into the Ex Nihilo Omnia/NeoTech subset menu causes crash

### ISSUE THREAD

**Issue by DatrixTHLK** [elix-x/Forever-Enough-Items#42]
You may know about this already but in case not here is the information. When looking up information on specific mods and the items/blocks they have within them, the game froze and then CTD after a few seconds. Specificly these two mods ATM. 

Version of Minecraft: 1.10.2
Version of FEI: 1.0.15
Version of JEI: 3.12.0.282
Version of Forge: 12.18.1.2094
Crash Report: http://pastebin.com/qr4DZetY
FML Log: http://www.pastefs.com/pid/6138

**Comment by Elix-x** [comment]
No, that's new.
Will be (is) fixed in 1.1.

**Comment by DatrixTHLK** [comment]
Thanks for the response and fix. I really like this mod.
