### ISSUE TITLE
Problem with FEI

### ISSUE THREAD

**Issue by firedarkness98** [elix-x/Forever-Enough-Items#43]
http://pastebin.com/XEwbvgD

Hello elix-x, 
I post this like you recommend me to do. What I put in the link is what i got when I tried to open  minecraft with the mods Forestry, Mantle (which  is necessary for Forestry or tinker construct I dont remember), tinker construct, mapwriter2 and the five mods who are needed if we want FEI ( which are Forever enough items, just enough items, light level overlay reloaded, chunk edge indicator and excore).
All of those mods are in 1.10.2

Thank you to find out my problem.

firedarkness98

**Comment by Elix-x** [comment]
Thank you very much for reporting it on github. I'll look into details in just a moment.

**Comment by Elix-x** [comment]
> This page has been removed!
> This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.

Did you set time out or something happened? Anyway, please reupload logs (i did not download them).

Also, while i'm here, CEI & LLOR are optional. So you can remove them if you don't need them.
Now, i know that i already said that on curse, but make sure that you have latest Excore & JEI.
Thank you.

_Meanwhile i'm thinking of pushing 1.1 alpha version..._

**Comment by firedarkness98** [comment]
http://pastebin.com/mBRkLgnY

For excore and JEI, i think tha t i have the latest version because i redownloaded them yesterday.

**Comment by Elix-x** [comment]
Are you sure that it's client-latest.log (can be called fml-client-latest.log)?

**Comment by Elix-x** [comment]
I released 1.0.16. Please confirm this is still a bug.

**Comment by DatrixTHLK** [comment]
I confirm this works.

**Comment by Rumpelstiltskinny** [comment]
#https://github.com/Elix-x/Excore/issues/3

nope, latest JEI (jei_1.10.2-3.12.8.328.jar) breaks FEI/Excore

**Comment by DatrixTHLK** [comment]
I cofirm this as well.
