### ISSUE TITLE
When opening world, game hang, no CTD

### ISSUE THREAD

**Issue by drakray** [elix-x/Forever-Enough-Items#44]
This get generated, but the game stay open, completly frozen before even redering world
http://pastebin.com/Fw75B8cS
got that since past JEI 286(last working version)

**Comment by Elix-x** [comment]
Does this happen everytime you open world?
Does this not happen if you remove FEI?

**Comment by drakray** [comment]
everyworld I tried to open, even new world
no more crash after I disabled(remove) FEI

**Comment by Elix-x** [comment]
Does this happen if you downgrade JEI (if you can)?
Does this happen with this build of JEI, but only with FEI & JEI (and required mods)?

Thanks.

**Comment by drakray** [comment]
If I rollback to JEI 286 all work fine
I don't know about removing other mods, as my personal pack have 63 active

**Comment by Elix-x** [comment]
Ok thanks. That's enough information.

I'll have to roll out either 1.1 alpha or 1.0.16 tomorrow, which will fix this.

**Comment by Elix-x** [comment]
I released 1.0.16. Please confirm this is still a bug.

**Comment by drakray** [comment]
I can get in game, so i'd say it's fixed, thanks! :D

**Comment by Elix-x** [comment]
You're welcome!
