### ISSUE TITLE
No response from Java after step 7/7 Launching minecraft

### ISSUE THREAD

**Issue by DatrixTHLK** [elix-x/Forever-Enough-Items#46]
Minecraft 1.10.2
Forge: 12.18.1.2094
JEI: 3.12.3.292
FEI: 1.0.16

FML: https://gist.github.com/DatrixTHLK/7ea21499a6b3105351165dc5d02f5e45

The only mod I've updated (meaning I just downloaded your mod and deleted the old version off my computer) today was yours. Chisel and bits didn't cause the issue as I've tested it.

**Comment by Elix-x** [comment]
So MC hangs. For how long? Does it respond eventually? Or it stays like it forever?

**Comment by DatrixTHLK** [comment]
Stays like that forever. Then my computer lags a bit and I have to close out of minecraft

**Comment by DatrixTHLK** [comment]
without the mod minecraft won't hang up on me.

**Comment by Elix-x** [comment]
Ok, this is a bit weird. Seems like cross mod interaction to me.

Do you have latest latest JEI build (from today)?

If you remove all mods besides FEI & dependencies, does it hang up?

**Comment by DatrixTHLK** [comment]
If JEI is at v. 3.12.3.292 today then yes this is the latest version of the mod for today since 19 hours ago. With just your mod jei excore and LLoverlay the game doesn't hang up on me at step 7/7...of course...which just means I'm going to go through each mod to figure out what the cause is and let the author of that mod know about it. Thanks for the help.

**Edit (5:43pm):**  So far the only mod that crashed the game was base metals (and its dependant mods) but I'm still testing out other mods incase that might not be the entire issue. Strange, before I rebooted my computer, the game would hang up and glitch out my computer in the process. If anymore details comes up I will share with you.

**Edit (9:16pm):** No other mods have caused any issues. It was just base metals and its dependent mods. I will close the issue now.

**Comment by Elix-x** [comment]
If you report it to [base metals' github](https://github.com/cyanobacterium/BaseMetals), please reference this issue with elix-x/Forever-Enough-Items#46.
That way, i'll be informed of the progress and will be able to help if it turns out issue is partially on my side.
Thanks!
