### ISSUE TITLE
crash without ExCore installed

### ISSUE THREAD

**Issue by jdratlif** [elix-x/Forever-Enough-Items#49]
When starting Minecraft with FEI but without ExCore, Minecraft crashes on startup. Perhaps the logs are clear to some people, but they weren't clear to me what the problem was. Then I remembered you needed ExCore, which fixed the problem.

Would you consider adding a message from Forge when you don't have ExCore installed saying you that need ExCore rather than just crashing? I've seen many other mods that have this feature (Tinkers's Construct with Mantle, RFTools with McJtyLib, eg. al.).

Thanks.

**Comment by Elix-x** [comment]
Forge is handling helpful screens, and while for TC, RFTools and others it works, it does not for FEI (and FEI specifically).
It's partially a forge bug, which still has not been fixed.
I would be thankful if you provided logs you based on, so i can either fix it in FEI or PR a fix to forge.
Thanks.

**Comment by jdratlif** [comment]
Attached crash logs. Didn't consider this could be a forge bug so I didn't bother with logs before. Sorry.

http://games.technoplaza.net/temp/fei-noexcorecrash.zip

Thanks.

**Comment by Elix-x** [comment]
No problems. Thanks for the report.
Crash line is from forge, so it's 50% forge bug.
I'll look into details when i'll have more time. Thanks for the crash meanwhile.
