### ISSUE TITLE
Crash with FEI and JEI

### ISSUE THREAD

**Issue by DatrixTHLK** [elix-x/Forever-Enough-Items#50]
Hi Mezz,

Thought I'd let you know about this. JEI updated.
https://github.com/mezz/JustEnoughItems/issues/535 

Minecraft 1.10.2
Forge: 12.18.2.2107
JEI: 3.12.8.238
FEI: 1.0.16

**EDIT:** (I meant this for you Elix_x). Apparently my cold is worse than I thought it was and the brain, it is fried.

**Comment by Elix-x** [comment]
Thanks for the report. I think i'll release 1.0.17 whenever i'll have access to my workspace, with more bugfixes.

**Comment by DatrixTHLK** [comment]
Sounds good, thanks for the quick response time.

**Comment by Rumpelstiltskinny** [comment]
ok @Elix-x, I see that you've seen this issue that I just duplicated @ #https://github.com/Elix-x/Excore/issues/3

_update: After looking further into this issue I see that it's related but not indentical (NoSuchFieldException: uidCacheEnabled) to my issue ref'd above. **AND** the latest JEI (###.328) is significantly smaller filesize (ok, only 4KB smaller) than the previous 327 build. Makes me wonder if that Curseforge acct was also hacked (as mDiyo's was with bogus TCon posted)_

**Comment by DatrixTHLK** [comment]
oh...I see, so someone has hacked the mod authors accts. and put in malicious code into their mods. Apparently, these hackers have a lot of spare time...well, that is what happens with the more popular mods out there. I'll need to be more careful in the future. Thanks @Rumpelstiltskinny

**Comment by Elix-x** [comment]
@Rumpelstiltskinny It's more or less same type of problem, so i closed it there and will fix em all in one go.
A few KB difference may easily happen, so don't worry... _Also, i'm first time hearing that curse account was hacked... Weird..._
