### ISSUE TITLE
Crash with FEI

### ISSUE THREAD

**Issue by DatrixTHLK** [elix-x/Forever-Enough-Items#53]
Hello again, Elix-x,

https://gist.github.com/DatrixTHLK/3ed469ae13abe206a38341202d875a47

Minecraft: 1.10.2
Forge: 12.18.2.2114
JEI: 3.13.0.334
FEI: 1.0.17

Goes up to step 6 of 7 and crashes on me (Finishing Up step.)

**Comment by Elix-x** [comment]
This was fixed in FEI 1.0.17**.1**.

**Comment by DatrixTHLK** [comment]
Oh...? I had no idea you updated. Thanks for letting me know though.
