### ISSUE TITLE
Newest version of JEI crashes with FEI

### ISSUE THREAD

**Issue by OfficialEsco** [elix-x/Forever-Enough-Items#54]
The Newest version of JEI is crashing FEI (Yes i downgraded to jei_1.10.2-3.13.0.341 and it worked)  

I'll be reporting this to you both

https://gist.github.com/OfficalEsco/3f19b73f49b0286023730f470b808739

**Comment by TDStewart** [comment]
Reported to both.  Works with JEI 342 but not 343.

https://gist.github.com/TDStewart/d052befe1a39645ed9ee68906d072316

**Comment by DatrixTHLK** [comment]
Can confirm this, but JEI isn't the cause of it. https://gist.github.com/DatrixTHLK/9c9828395f15dff5aa7275190f8cfc42

Well with JEI updating it was bound to break FEI at some point.
