### ISSUE TITLE
/feiop on Single Player "Something went wrong"

### ISSUE THREAD

**Issue by Malkierian** [elix-x/Forever-Enough-Items#57]
And that's all I get.  No op privileges, no utilities functionality, and as far as I can tell, nothing in the logs.  Is there a reason why you can't assume OP for single-player for the player?

**Comment by Malkierian** [comment]
For the record, it's not terribly clear that all you have to do on single player is /feiop with no arguments...  Still, the question stands, why not just assume the permission on SP?

**Comment by Elix-x** [comment]
@Malkierian Are cheats enabled? Running with no args means running only `/feiop`.

If cheats are enabled and you're in creative, you should be auto opped. Though sometimes it takes some time before it auto ops you after opening a world.

**Comment by Malkierian** [comment]
Yes, I know what running with no args, but the instructions on your Forge page don't say that clearly.  `/feiop (single player/lan)` didn't mean only `/feiop` to me.  I was trying to put in "lan" or "singleplayer" or whatever as an arg XD

But, I wasn't in creative, I was in survival, so I guess that explains not auto-opping.  I just figured, since the whole point of it was to have a few cheat-like capabilities, that user management would be a non-issue if it's single player.

**Comment by Elix-x** [comment]
So is everything working now?

**Comment by Malkierian** [comment]
Yes, it works, though I would request some clarification in the instructions.

**Comment by Elix-x** [comment]
Ok. Will take this into account.
