### ISSUE TITLE
[Suggestion] Add a global B:cheatItemsEnabled=true function to cheat mode profile

### ISSUE THREAD

**Issue by GazbonicAcid** [elix-x/Forever-Enough-Items#58]
Please add a global B:cheatItemsEnabled=true function to the cheat mode profile.
Mezz has asked that I go through due process and ask your first.
https://github.com/mezz/JustEnoughItems/issues/648

**Comment by Elix-x** [comment]
I'll have to explain a few things. But first i want to make sure:
You want to have enable cheat items mode for ALL profiles, right?

**Comment by GazbonicAcid** [comment]
No.
Only for Cheat Mode profile,
but globally across all **_worlds_** without needing to manually set it each time I log into a new world for the first time.

**Comment by Elix-x** [comment]
Then what you need isn't affected by config you're asking for. Not at all.

**Comment by Elix-x** [comment]
I call it JEI overlay override, because i override JEI overlay **COMPLETELY**.
The only 2 things that you need with FEI to cheat items in are (**both** have to be true):
- Profile -> Element Settings -> JEI Override -> Allow Give/Delete Items
- /feiop

**Comment by Elix-x** [comment]
Now, if `B:cheatItemsEnabled` actually affects something, this is a bug.

**Comment by GazbonicAcid** [comment]
I would like to wholeheartedly apologize for my misunderstanding.
I added B:cheatItemsEnabled=true to the cheat mode global jei.cfg while the cheat mode profile was loaded.
It would appear that the issue I was having was that since I was already in cheat mode profile,
FEI did not see the need (which there was none) to re-override the jei config.
I didn't even originally bother to try switching profiles back and forth.
I was wrong.
I am trully sorry.
I hope that you can forgive me.

**Comment by GazbonicAcid** [comment]
That means this issue can be labeled "invalid" and closed.

**Comment by GazbonicAcid** [comment]
unless ofcourse if FEI is supposed to ignore JEI's B:cheatItemsEnabled setting.
Edit:
If that's the case,
then every version combination of FEI and JEI I've *ever* used has had this bug.

**Comment by Elix-x** [comment]
@majix560 `unless ofcourse if FEI is supposed to ignore JEI's B:cheatItemsEnabled setting` it is. What happens when you change it's value?
And what happens if then you change settings with JEI override settings in-game?

**Comment by GazbonicAcid** [comment]
If the world config says B:cheatItemsEnabled=false and the setting is *not* in jei global config,
*including* in the jei config ovveride,
then I am completely unable to cheat items in until I set B:cheatItemsEnabled to true in the jei config file overide.
This is even while the non-config-file JEI override option "Can Give Items" is checked.
Though once I set B:cheatItemsEnabled to true in the config-file jei override, even in just the cheat mode profile, it works.
Wierd thing is,
is that un-checking the "Can Give Items" with B:cheatItemsEnabled set to true successfully stops cheating items in.
Even though "Can Give Items" to true and B:cheatItemsEnabled=false doesn't allow cheating items in.

**Comment by Elix-x** [comment]
In the inventory screen, is there JEI settings button (with wrench icon)?

**Comment by GazbonicAcid** [comment]
no

**Comment by GazbonicAcid** [comment]
to set options in jei config, I edit cheat-mode profile, edit JEI override, then left click on the "JEI" button on that page.
Edit:
There's also the choice of manually editing said config file.
*Including* in the FEI jei profile override files.

**Comment by Elix-x** [comment]
That should be enough details. Will be fixed in next release (alpha).
Which MC version are you using?

**Comment by GazbonicAcid** [comment]
1.10.2

**Comment by Elix-x** [comment]
Thanks!
Sadly, next release (alpha) will be for 1.11, and i won't be able to fix it in 1.10.2.

**Comment by GazbonicAcid** [comment]
Oh well, at least I have the work around of adding the jei built-in cheat option to cheat mode profile's override for the jei global config.

**Comment by GazbonicAcid** [comment]
I have a question though.
Why the default saved inventory of a torch in the off-hand slot named a seemingly uuid long string,
with a 2 character censored name for the button,
specifically only in utilities mode?
I'm assuming it was something from the dev environment to test something that you didn't take out.

**Comment by Elix-x** [comment]
_I wonder what decrypting this would give you?_

**Comment by GazbonicAcid** [comment]
So basically it's an easter egg then?

**Comment by Elix-x** [comment]
_That may or may not have been there for 7 months now._
