### ISSUE TITLE
Unable to configure

### ISSUE THREAD

**Issue by Thiana** [elix-x/Forever-Enough-Items#6]
The profile configuration is acting differently depending on how large the screen is. When it's full screen I see 5 sections to configure (B) but none of those sections react to clicks. When it's not full screen (A) only 2 sections are visible (JEI, Utilities) and both can be selected for further configuration (C). 

When in fullscreen mode (B), the logfile gets spammed with:
[00:07:58] [Client thread/ERROR]: ########## GL ERROR ##########
[00:07:58] [Client thread/ERROR]: @ Post render
[00:07:58] [Client thread/ERROR]: 1281: Invalid value

Thanks.

Versions:
MC 1.9
Forge 1868
ExCore 1.5.2-1.9
FEI 1.0.5-1.9
JEI 1.9-3.3.2.196
LLOverlayReloaded 1.0.7-mc1.9
More Overlays 1.2-mc1.9

Screenshots:
(A) Config options available when not-fullscreen
![2016-05-02_00 07 03](https://cloud.githubusercontent.com/assets/405832/14947017/3d417b00-0ffa-11e6-8d59-4eab29b20834.png)

(B) Config options available when fullscreen
![2016-05-02_00 07 46](https://cloud.githubusercontent.com/assets/405832/14947020/414c0f9e-0ffa-11e6-8732-f298ac75821f.png)

(C) JEI Configuration, accessible only when not-fullscreen
![2016-05-02_00 09 03](https://cloud.githubusercontent.com/assets/405832/14947021/43368988-0ffa-11e6-8c0c-b24b87c2ef46.png)

**Comment by Elix-x** [comment]
I'll check full screen mode. Meanwhile, this is list of elements, meaning that you can scroll, or drag it with your mouse to show elements below / above.

I'll also check what is causing gl error (and it seems that it causes configuration screens to become invisible).

Thanks for the report!

**Comment by Thiana** [comment]
Everything (including fullscreen) is working correctly with the new version. Thank you :)

**Comment by Elix-x** [comment]
No problems!
