### ISSUE TITLE
Subset enhancement

### ISSUE THREAD

**Issue by Thiana** [elix-x/Forever-Enough-Items#7]
Could you please consider three refinements to Item Subsets?

(1) Sort the list of mods alphabetically.
(2) Allow the size of the subset window to be altered so we can see more mods without scrolling. As it is the list only uses the top 30% of the screen.
(3) If we shift-click the mod name could you have it paste the @modname to jei's search field? A single scrollable list is ok for a quick overview but for mods that have dozens or more items it's a little awkward.

Thank you.

**Comment by Elix-x** [comment]
1) Doable. Expect in next update.
2) I'll think how it can be done.
3) Already in my to-do list :) .
