### ISSUE TITLE
Press P to manage profiles 

### ISSUE THREAD

**Issue by bart1ebee** [elix-x/Forever-Enough-Items#8]
I have modular storage installed and pressing P in the search bar for modular storage will bring up the mange profiles too. Kind of related to issue #5 version 1.0.5 or 1.0.6 can't remember what version is installed and I'm not at my machine.

**Comment by Elix-x** [comment]
Yep. And i'm accepting suggestions on how i should change it. As temporary solution, in 1.0.7, you will have to press ctrl+P.

**Comment by Elix-x** [comment]
I'll create a separate issue for this.
