### ISSUE TITLE
hardcore

### ISSUE THREAD

**Issue by m1jordanallen** [elix-x/Forever-Enough-Items#9]
Without the use of cheats on hardcore or when not enabling cheats in survival, it's a pain to fiddle with opening to lan and using commands to get many aspects of the mod to work (magnet, time, etc).  I may be missing something in the options.

**Comment by Elix-x** [comment]
If you want to be able to fidle with time (and other things) without moderator permission, you can go to config/Forever Enough Items/static.cfg and you'll see permission category. Just change each one you want to use without permission to "USER".

**Comment by m1jordanallen** [comment]
thank you for the response!  This is exactly what I was hoping for :)

**Comment by Elix-x** [comment]
No problems!
